version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: product-catalog-app
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: catalog_db
            DB_USERNAME: postgres
            DB_PASSWORD: 123
        networks:
            - catalog_network

    db:
        image: postgres:13
        container_name: product-catalog-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: catalog_db
        ports:
            - 5432:5432
        networks:
            - catalog_network

networks:
    catalog_network:
        driver: bridge
